//
//  Quotes.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Quotes: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _person: String?
    var _free: NSNumber?
    var _quote: String?
    
    class func dynamoDBTableName() -> String {

        return "quotes-mobilehub-979977669-Quotes"
    }
    
    class func hashKeyAttribute() -> String {

        return "_person"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_person" : "Person",
               "_free" : "Free",
               "_quote" : "Quote",
        ]
    }
}
